apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metis
  labels:
    app: metis
    env: production
    criticality: med
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: metis
        env: production
        criticality: med
    spec:
      containers:
        - name: metis
          image: registry.repositive.io:5000/metis:${TAG}
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: metis-production
                  key: db-uri
            - name: RABBIT_URI
              valueFrom:
                secretKeyRef:
                  name: rabbit-urls-production
                  key: rabbit
            - name: ELASTIC_URI
              value: "http://elastic:9200"
          resources:
            requests:
              memory: 128Mi
              cpu: 0.01
      imagePullSecrets:
        - name: regsecret
