apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metis
  namespace: discover
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: metis
    spec:
      containers:
      - env:
        - name: RABBIT_URI
          valueFrom:
            secretKeyRef:
              key: rabbit
              name: rabbit-urls-production
        - name: ELASTIC_URI
          value: http://elastic:9200
        image: registry.repositive.io:5000/metis:${TAG}
        name: metis
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
      imagePullSecrets:
      - name: regsecret
